name: AutoReleaseOnCommit
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/release-with-commit@latest
        with:
          regexp: ".*"
          regexp_options: "us"
          release_name: "Release: $1"
          tag_name: "tag:$1"
          body: ""
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
